###############################################################################
#
# Configuration for Microsoft NNI
# Reference: https://nni.readthedocs.io/en/latest/Tutorial/ExperimentConfig.html
#
# Launch the experiment:
# - replace the PROF_DIR and ENV_DIR with your own project and environment paths respectively.
# - configure the experiment (e.g. changing the duration, concurrency, and tuner etc.)
# - execute the following command: $ nnictl create --config ${PROJ_DIR}/exps/example/config.yaml --debug --port ${PROT_NUM}
#
###############################################################################

experimentName: "CLVIS-CHLG (config 1)"
experimentWorkingDirectory: "/home/xduan7/projects/clvis-chlg/logs/nni"

maxExperimentDuration: 14d
maxTrialNumber: 1000
searchSpaceFile: "search_space.json"
useAnnotation: false

trialConcurrency: 6
trialGpuNumber: 1
trialCodeDirectory: "/home/xduan7/projects/clvis-chlg"
trialCommand: PYTHONPATH="/home/xduan7/projects/clvis-chlg:${PYTHONPATH}" /home/xduan7/software/anaconda3/envs/clvis-chlg/bin/python train.py --config 1 --benchmark --clf_logit_calibr batchnorm --tst_time_aug 18

tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize

trainingService:
  platform: local
  useActiveGpu: true
  maxTrialNumberPerGpu: 2
